apiVersion: v1
kind: Service
metadata:
    name: jenkins-service
    labels:
        name: jenkins-service
        app: demo-voting-app
      
spec:
    type: NodePort
    ports:
      - targetPort: 8080
        port: 8080
        nodePort: 30080
    selector:
        name: jenkins-pod
        app: demo-voting-app
        
